In [1]:
#Importing Numpy and creating a numpy darray object
import numpy as np
arr1=np.array([100,200,400,500])
print(arr1)

[100 200 400 500]


In [2]:
#Creating a 2D array
arr2=np.array([[1,2,3,4],[5,6,7,8]])

#Creating a 3D array
arr3=np.array([[[1,2,3],[3,4,5],[5,6,7]]])

print(arr2)
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3]
  [3 4 5]
  [5 6 7]]]


In [3]:
#Checking the Array Shape
print('Shape:' ,arr3.shape)

#Checking the Array Dimension
print('Array dimension: ',arr3.ndim)

#Checking the Array Data type
print('Array DataType: ',arr3.dtype)

#Checking the Array total size(in bytes)
print('Array size in bytes: ',arr3.nbytes)

#Checking the No of elements in the Array
print('Item no: ',arr3.itemsize)

Shape: (1, 3, 3)
Array dimension:  3
Array DataType:  int64
Array size in bytes:  72
Item no:  8


In [4]:
arr1=np.array([1,2,3,4,5],dtype='int16')
print(arr1.dtype)

arr2=np.array([1,2,3,4,5],dtype='int32')
print(arr2.dtype)

arr3=np.array([1,2,3,4,5],dtype='int64')
print(arr3.dtype)

int16
int32
int64


In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
#Getting specific row
print(arr)

#Getting all the elements of first row
print(arr[0,:])

#Getting all the elements of 2nd column
print(arr[:,1])

#Getting all the elements of 1st column
print(arr[:,0])


#Slice from the index 3 from the end to index 1 from the end
arrx = np.array([1, 2, 3, 4, 5, 6, 7])
print(arrx[-3:-1])

#Slice from the index 3 to the end
print(arrx[3:])

#Slice from the start to index 3
print(arrx[:3])

#Return every other element from the entire array
print(arrx[::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[2 7]
[1 6]
[5 6]
[4 5 6 7]
[1 2 3]
[1 3 5 7]


In [6]:
#Creating an array of dimensions 3x4 with all values set to zero
arr0=np.zeros((3,4))
print(arr0)

#Creating an array of dimensions 1x2 with all values set to one
arr1=np.ones((1,2))
print(arr1)

#Creating an identity 2d matrix
arr=np.identity(2)
print(arr)

#Creating a 2d matrix with all values set to 93.93
arr=np.full((2,2),93.93)
print(arr)

#Creating a 2d matrix that resembles an existing one
#Here arr dimension will resemble arr but the values will be set to 98
arr1=np.full_like(arr,98)
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]]
[[1. 0.]
 [0. 1.]]
[[93.93 93.93]
 [93.93 93.93]]
[[98. 98.]
 [98. 98.]]


In [7]:
#Creating a matrix with random float values
#First we are specifying the range ie our values will range from -1 to 10
#Secondly we are specifying the size of the array
arr=np.random.uniform(-1,10,size=(4,4))
print(arr)

[[ 4.63685244  0.58887642  6.40364553  4.07122218]
 [ 4.01236814  4.05895482  1.24203227 -0.64471923]
 [ 5.54267986  0.26919583  3.4728511   0.88366986]
 [-0.75583622  2.66136901  8.46109085  4.1880052 ]]
